<?php

namespace App\Enum;

use Nasyrov\Laravel\Enums\Enum;

class FeeEnum extends Enum
{
    const REGISTRATION_A = 1; //SPEAKERS/SESSION AND WORKSHOP CHAIRS
    const REGISTRATION_B = 2; //LOCAL PDS MEMBER
    const REGISTRATION_C = 3; //LOCAL RESIDENT
    const REGISTRATION_D = 4; //LOCAL NON PDS RESIDENT
    const REGISTRATION_E = 5; //LOCAL NON PDS MDS
    const REGISTRATION_F = 6; //INTERNATIONAL LADS MEMBER
    const REGISTRATION_G = 7; //INTERNATIONAL LADS RESIDENT
    const REGISTRATION_H = 8; //INTERNATIONAL NON LADS MEMBERS
    const REGISTRATION_I = 9; //INTERNATIONAL LADS OFFICERS
    const REGISTRATION_J = 10; //LOCAL PDS COA, BOD, OC

    const WORKSHOP_A_AESTH = 11; //LOCAL PDS MEMBER
    const WORKSHOP_A_LASER = 12;
    const WORKSHOP_A_BOTH = 13;

    const WORKSHOP_B_AESTH = 14;//LOCAL RESIDENT
    const WORKSHOP_B_LASER = 15;
    const WORKSHOP_B_BOTH = 16;

    const WORKSHOP_C_AESTH = 17;//INTERNATIONAL LADS
    const WORKSHOP_C_LASER = 18;
    const WORKSHOP_C_BOTH = 19;

    const WORKSHOP_D_AESTH = 20;//INTERNATIONAL NON LADS
    const WORKSHOP_D_LASER = 21;
    const WORKSHOP_D_BOTH = 22;

    const WORKSHOP_E_AESTH = 23;//INTERNATIONAL RESIDENTS
    const WORKSHOP_E_LASER = 24;
    const WORKSHOP_E_BOTH = 25;

    const WORKSHOP_F_AESTH = 26;//SPEAKERS/SESSION AND WORKSHOP CHAIRS
    const WORKSHOP_F_LASER = 27;
    const WORKSHOP_F_BOTH = 28;

    const WORKSHOP_G_AESTH = 29;//INTERNATIONAL LADS OFFICER
    const WORKSHOP_G_LASER = 30;
    const WORKSHOP_G_BOTH = 31;

    const WORKSHOP_H_AESTH = 32;//LOCAL PDS COA, BOD, OC
    const WORKSHOP_H_LASER = 33;
    const WORKSHOP_H_BOTH = 34;

    const WORKSHOP_I_AESTH = 35;//LOCAL NON PDS ROAI
    const WORKSHOP_I_LASER = 36;
    const WORKSHOP_I_BOTH = 37;
}