<?php

return [
    'APP_URL' => env('APP_URL'),
    'CONVENTION_URL' => env('CONVENTION_URL'),
    'DEFAULT_IMG' => env('DEFAULT_IMG'),

    'DEFAULT_ADMIN_PASSWORD' => env('DEFAULT_ADMIN_PASSWORD'),
    'DEFAULT_MEMBER_PASSWORD' => env('DEFAULT_MEMBER_PASSWORD'),
    'DEFAULT_SPONSOR_PASSWORD' => env('DEFAULT_SPONSOR_PASSWORD'),
    'DEFAULT_SPONSOR_EXHIBITOR_PASSWORD' => env('DEFAULT_SPONSOR_EXHIBITOR_PASSWORD'),

    'FOREX_USD_URL' => env('FOREX_USD_URL'),
    'CREATE_FOREX' => env('CREATE_FOREX', true)
];